# Documentation at http://goreleaser.com

builds:
  - env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64 ]

archives:
  - replacements:
      darwin: macOS
    format: binary

dockers:
  - image_templates:
      - "skpr/pod-termination-logger:latest"
      - "skpr/pod-termination-logger:{{ .Tag }}"
    build_flag_templates: [ "--pull" ]

release:
  prerelease: auto
  github:
    owner: skpr
    name: pod-termination-logger